# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = [
	"Disconnecting VANILLA connection attempt",
	"Channels ",
    "Hanging entity",
	"Is the server overloaded",
	"moved too quickly!",
	"Ignored advancement",
    "DeeperAndDarker",
	"Tried to access a block entity",
	"Empty or non-existent pool",
	"vecbegin", 
    "[com.ishland.vmp.common.networking.priority.PacketPriorityHandler]",
	"was slain by fake", 
    "NetherPortalFix",
	"Async chunk loading for player",
	"Tried to load a",
	"Loading PlayerData for player",
	"owo",
	"Paragon",
	"WandsMod",
	"moved wrongly!",
	"[net.projectile_damage.mixin.ServerWorldMixin]",
	"Launching modified arrow",
	"Priority overwritten for player",
	"Tried to register an overly",
	"No data fixer registered",
	"Ignoring unknown attribute",
	"Loading PlayerProfile for player",
	"protocol version: 2.0",
	"Exceeded time limit of",
	"Exception loading blockstate definition",
	"Sampler2",
	"Failed to load model",
	"Model loader",
	"Failed to load ModMenuApi",
	"If this is a development environment you can ignore this message",
	"Failed to load book",
	"This entry will be ignored",
	"evaluating model definition",
	"Falling back to vanilla logic",
	"Couldn't parse element",
	"Parsing error loading custom advancement",
	"Durations have no impact on this type of recipe.",
	"suppressed exception",
	"Using missing texture",
	"Unable to load model",
	"Unable to bake model",
	"Missing sound for event",
	"Couldn't load certain entries with the tag",
	"Falling back to vanilla",
	"Couldn't load advancement",
	"Couldn't load advancement",
	"missing from registry, but requested!",
	"Could not decode GlobalLootModifier with json id",
	"Invalid icon item stack",
	"Invalid extra recipe mapping"
    ]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Disconnecting VANILLA connection attempt", "Channels "]